-- SET FOREIGN KEYS
alter table PHONES
add FOREIGN KEY (CPU_ID) REFERENCES CPUS(ID);
alter table PHONES
  add FOREIGN KEY (GPU_ID) REFERENCES GPUS(ID);
alter table PRODUCTION
  add FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID);
alter table PRODUCTION
  add FOREIGN KEY (SHOP_ID) REFERENCES SHOP(ID);
alter table ORDERS
  add FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTION(ID);
alter table ORDERS
  add FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);
alter table SHOP
  add FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID);
alter table PRODUCTION
  add FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURERS(ID);
alter table PRODUCTION
  add FOREIGN KEY (PHONE_ID) REFERENCES PHONES(ID);
alter table PHONES
  add FOREIGN KEY (CPU_ID) REFERENCES CPUS(ID);
alter table PHONES
  add FOREIGN KEY (GPU_ID) REFERENCES GPUS(ID);
alter table MANUFACTURERS
  add FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID);
alter table SUPPLIERS
  add FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID);
alter table CUSTOMERS
  add FOREIGN KEY (CITIZENSHIP_COUNTRY_ID) REFERENCES COUNTRIES(ID);
