CREATE OR REPLACE PACKAGE CRUD_OPS AS
  TYPE CUSTOMER_ROW_TYPE IS RECORD
  (
    ID INT,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    MIDDLENAME VARCHAR(255),
    REGISTER_ADDRESS VARCHAR(255),
    CITIZENSHIP_COUNTRY_ID INT
  );
  TYPE CUSTOMER_TABLE_TYPE IS TABLE OF CUSTOMER_ROW_TYPE;
  PROCEDURE ADD_ORDER(
    CUSTOMER_FIRST_NAME  CUSTOMERS.FIRSTNAME%TYPE,
    CUSTOMER_MIDDLE_NAME CUSTOMERS.MIDDLENAME%TYPE,
    CUSTOMER_LAST_NAME CUSTOMERS.LASTNAME%TYPE,
    CUSTOMER_REGISTER_ADDERESS CUSTOMERS.REGISTER_ADDRESS%TYPE,
    COUNTRY COUNTRIES.NAME%TYPE,
    PRODUCT PHONES.NAME%TYPE
  );-- RETURN INT;
  FUNCTION COUNT_ORDERS_OF_CUSTOMER(CUST_ID INT) RETURN int;
  PROCEDURE UPDATE_CUSTOMER_INFO(
    CUSTOMER_FIRSTNAME CUSTOMERS.FIRSTNAME%TYPE,
    CUSTOMER_MIDDLENAME CUSTOMERS.MIDDLENAME%TYPE,
    CUSTOMER_LASTNAME CUSTOMERS.LASTNAME%TYPE,
    NEXT_CUSTOMER_FIRSTNAME CUSTOMERS.FIRSTNAME%TYPE,
    NEXT_CUSTOMER_MIDDLENAME CUSTOMERS.MIDDLENAME%TYPE,
    NEXT_CUSTOMER_LASTNAME CUSTOMERS.LASTNAME%TYPE,
    CUSTOMER_REGISTER_ADDERESS CUSTOMERS.REGISTER_ADDRESS%TYPE,
    COUNTRY COUNTRIES.NAME%TYPE
  );
  PROCEDURE DELETE_CUSTOMER(
    CUSTOMER_FIRSTNAME CUSTOMERS.FIRSTNAME%TYPE,
    CUSTOMER_MIDDLENAME CUSTOMERS.MIDDLENAME%TYPE,
    CUSTOMER_LASTNAME CUSTOMERS.LASTNAME%TYPE
  );
  CONSTRAINT_VIOLATED EXCEPTION;
  PRAGMA EXCEPTION_INIT(CONSTRAINT_VIOLATED, -2290);
END CRUD_OPS;